### ISSUE TITLE
iOS: Use server side author photos

### ISSUE THREAD

**Issue by ovidiumse** [ovidiumse/comori-od#41]
Use server-side author photos for the following calls:

- /od/authors
- /od/volumes
- /od/books
- /od/recommended
- /od/trendingarticles
- /od/recentlyaddedbooks (needs "include_author_photo" url param)

**Comment by ovidiumse** [comment]
The above endpoints provide author photo links on testapi

**Comment by Yakis** [comment]
Need an "photo_url" field in article for LastRead and other cases.

**Comment by ovidiumse** [comment]
This is done.
