### ISSUE TITLE
Author photo url for articles

### ISSUE THREAD

**Issue by Yakis** [ovidiumse/comori-od#43]
We need a field with author photo url for both live and static articles.

**Comment by ovidiumse** [comment]
This is resolved (locally at the moment) for static articles, which seemed the hardest to achieve. 
The author photo url will be provided as 'author-photo-url-lg' and 'author-photo-url-sm'.
Please note that as we don't have photos available for all authors, the 'author-photo-url-*' fields can be missing for some articles.

**Comment by ovidiumse** [comment]
And the best thing is that once added to the static articles, the photo-urls will be available EVERYWHERE, because those static article files are actually uploaded to ES with the photo-urls embedded.

**Comment by Yakis** [comment]
That's great! Let me know when it's up on testapi.

**Comment by ovidiumse** [comment]
This should now be available on testapi. Please confirm.

**Comment by Yakis** [comment]
Yes, looks good.
